[package]
name = "cryptofuzz-substrate-bn-harness"
version = "0.1.0"
authors = ["Guido Vranken <guidovranken@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
substrate-bn = { version = "0.6.0", default-features = false }
libc = "0.2.0"
