[package]
name = "schnorr_fun_harness"
version = "0.1.0"
authors = ["Guido Vranken <guidovranken@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]
schnorr_fun = "0.6"
sha2 = "0.9"
rand = "0.8"
libc = "0.2.0"
